"""Tests for converting OctoMap .bt files into A* occupancy grids."""

from pathlib import Path

import numpy as np
import pytest

from pathfinding import octomap_grid


def child_index_for_key(key, child_depth):
    """Return the child index used by OctoMap for a target leaf key."""
    bit_position = octomap_grid.TREE_DEPTH - child_depth
    child_index = 0
    for axis, bit in enumerate((1, 2, 4)):
        if (key[axis] >> bit_position) & 1:
            child_index |= bit
    return child_index


def add_leaf(root, key, occupied):
    """Insert a leaf into a compact test octree trie."""
    node = root
    for child_depth in range(1, octomap_grid.TREE_DEPTH + 1):
        child_index = child_index_for_key(key, child_depth)
        if child_depth == octomap_grid.TREE_DEPTH:
            node[child_index] = occupied
        else:
            node = node.setdefault(child_index, {})


def serialize_node(node):
    """Serialize a test trie node using OctoMap's two-bit child masks."""
    masks = [0, 0]
    child_payloads = []
    for child_index in range(8):
        child = node.get(child_index)
        if child is None:
            continue

        if isinstance(child, dict):
            low_bit, high_bit = 1, 1
            child_payloads.append(serialize_node(child))
        elif child is False:
            low_bit, high_bit = 1, 0
        else:
            low_bit, high_bit = 0, 1

        byte_index = 0 if child_index < 4 else 1
        bit_pair = child_index % 4
        masks[byte_index] |= low_bit << (bit_pair * 2)
        masks[byte_index] |= high_bit << (bit_pair * 2 + 1)

    return bytes(masks) + b"".join(child_payloads)


def write_test_bt(tmp_path, leaves, resolution=1.0):
    """Write a minimal OctoMap .bt file for parser tests."""
    root = {}
    for key, occupied in leaves:
        add_leaf(root, key, occupied)

    payload = serialize_node(root)
    header = (
        "# Octomap OcTree binary file\n"
        "# generated by tests\n"
        "id OcTree\n"
        f"size {len(leaves)}\n"
        f"res {resolution}\n"
        "data\n"
    )
    path = Path(tmp_path) / "map.bt"
    path.write_bytes(header.encode("utf-8") + payload)
    return path


def test_parse_bt_file_reads_free_and_occupied_leaves(tmp_path):
    """The .bt parser should recover the leaf keys and binary occupancy state."""
    free_key = (32768, 32768, 32768)
    occupied_key = (32769, 32768, 32768)
    path = write_test_bt(tmp_path, [(free_key, False), (occupied_key, True)])

    parsed = octomap_grid.parse_bt_file(path)

    assert parsed.tree_id == "OcTree"
    assert parsed.resolution == 1.0
    leaves_by_key = {leaf.key: leaf.occupied for leaf in parsed.leaves}
    assert leaves_by_key == {free_key: False, occupied_key: True}


def test_bt_file_to_numpy_grid_matches_astar_axis_order(tmp_path):
    """Converted grids should use grid[z, y, x] while public indices are x/y/z."""
    path = write_test_bt(
        tmp_path,
        [
            ((32768, 32768, 32768), False),
            ((32769, 32768, 32768), True),
        ],
    )

    converted = octomap_grid.bt_file_to_numpy_grid(
        path,
        bounds=((0.0, 0.0, 0.0), (2.0, 1.0, 1.0)),
        padding=0.0,
    )

    assert converted.origin == (0.0, 0.0, 0.0)
    assert converted.grid.shape == (1, 1, 2)
    np.testing.assert_array_equal(converted.grid, np.array([[[0, 1]]], dtype=np.uint8))
    assert converted.world_to_grid((0.5, 0.5, 0.5)) == (0, 0, 0)
    assert converted.grid_to_world((1, 0, 0)) == (1.5, 0.5, 0.5)


def test_bt_file_to_numpy_grid_can_infer_bounds_and_include_goal_points(tmp_path):
    """Inferred bounds should include known leaves plus requested endpoint padding."""
    path = write_test_bt(tmp_path, [((32768, 32768, 32768), False)])

    converted = octomap_grid.bt_file_to_numpy_grid(
        path,
        include_points=((3.0, 0.5, 0.5),),
        padding=1.0,
        unknown_is_occupied=False,
    )

    assert converted.origin == (-1.0, -1.0, -1.0)
    assert converted.grid.shape[2] >= 5
    assert converted.grid[1, 1, 1] == 0
    assert converted.contains_index(converted.world_to_grid((3.0, 0.5, 0.5)))


def test_bt_file_to_numpy_grid_rejects_non_positive_planning_resolution(tmp_path):
    """A dense planning grid cannot be created at zero or negative resolution."""
    path = write_test_bt(tmp_path, [((32768, 32768, 32768), False)])

    with pytest.raises(ValueError, match="planning_resolution"):
        octomap_grid.bt_file_to_numpy_grid(path, planning_resolution=-1.0)


def test_bt_file_to_numpy_grid_requires_bounds_for_empty_maps(tmp_path):
    """Empty saved maps need explicit bounds because there are no leaf extents."""
    path = write_test_bt(tmp_path, [])

    with pytest.raises(ValueError, match="empty OctoMap"):
        octomap_grid.bt_file_to_numpy_grid(path)


def test_compute_child_key_rejects_invalid_depths():
    """Malformed trees should fail before shifting keys with invalid depths."""
    with pytest.raises(ValueError, match="between 1 and"):
        octomap_grid.compute_child_key((32768, 32768, 32768), 0, 0)


def test_coordinate_helpers_match_octomap_depth_conventions():
    """Coordinate helpers should cover root, leaf, and intermediate depths."""
    grid = octomap_grid.OctomapGrid(
        grid=np.zeros((1, 2, 3), dtype=np.uint8),
        origin=(-1.0, -1.0, -1.0),
        resolution=1.0,
        occupied_leaves=0,
        free_leaves=1,
    )

    assert octomap_grid.key_to_coord(octomap_grid.TREE_MAX_VAL, 0, 1.0) == 0.0
    assert octomap_grid.key_to_coord(octomap_grid.TREE_MAX_VAL, 15, 1.0) == 1.0
    assert octomap_grid.node_size_at_depth(14, 0.5) == 2.0
    assert grid.contains_index((2, 1, 0)) is True
    assert grid.contains_index((3, 1, 0)) is False


def test_parse_bt_file_rejects_malformed_headers(tmp_path):
    """Malformed files should fail with clear header errors."""
    bad_magic = Path(tmp_path) / "bad_magic.bt"
    bad_magic.write_text("not an octomap\n", encoding="utf-8")

    with pytest.raises(ValueError, match="missing"):
        octomap_grid.parse_bt_file(bad_magic)

    no_data = Path(tmp_path) / "no_data.bt"
    no_data.write_text(
        "# Octomap OcTree binary file\nid OcTree\nsize 0\nres 1.0\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="data section"):
        octomap_grid.parse_bt_file(no_data)

    missing_id = Path(tmp_path) / "missing_id.bt"
    missing_id.write_bytes(b"# Octomap OcTree binary file\nres 1.0\ndata\n\x00\x00")
    with pytest.raises(ValueError, match="missing an id"):
        octomap_grid.parse_bt_file(missing_id)

    invalid_resolution = Path(tmp_path) / "invalid_resolution.bt"
    invalid_resolution.write_bytes(b"# Octomap OcTree binary file\nid OcTree\nres 0.0\ndata\n\x00\x00")
    with pytest.raises(ValueError, match="invalid resolution"):
        octomap_grid.parse_bt_file(invalid_resolution)


def test_parse_bt_file_rejects_truncated_binary_nodes(tmp_path):
    """Binary node masks must contain both child-mask bytes."""
    truncated = Path(tmp_path) / "truncated.bt"
    truncated.write_bytes(b"# Octomap OcTree binary file\nid OcTree\nres 1.0\ndata\n\xff")

    with pytest.raises(ValueError, match="ended inside a node"):
        octomap_grid.parse_bt_file(truncated)
